<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'mikeraic_pres369');
define('_DB_USER_', 'mikeraic_pres369');
define('_DB_PASSWD_', '[8Fcc3.SP8');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'pdt5e42kvcfbfbfvyyaiw7eumbqpk5f0rmwpy8xlbmbqgmgq9rdi0wxr');
define('_COOKIE_IV_', '5dhowcwp');
define('_PS_CREATION_DATE_', '2014-10-29');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'PEHuke3GFJTm1nqHAwapzq83z8hOdnPX');
define('_RIJNDAEL_IV_', '6G8h6GsQXVLNddJcRsZiSQ==');
